tier4/caret_report

- README.md
- analyze_node/analyze_node.py
- analyze_path/analyze_path.py
- analyze_path/template_path.html
- make_report.sh
> feat(path): add option to output message_flow

- README.md
@takeshi-iwanari  
I found some simple mistake in README. Please check them when you are not busy.
> fix: corrected some careless mistakes.

- analyze_path/template_path.html
- check_callback_sub/template_report_sub.html
- check_callback_timer/template_report_timer.html
- docker/Dockerfile
- docker/README.md
- docker/entrypoint.sh
- make_report.sh
- top/template_report_top.html
> ci: fix broken code by autofix

- docker/Dockerfile
> ci: fix docker file

- README.md
- docker/Dockerfile
- docker/README.md
> chore: add information for galactic

- check_callback_sub/README.md
- sample_autoware/README.md
- sample_autoware/target_path.json
> ci: fix spell check

- .github/workflows/test_autoware.yaml
> ci: fix docker tag in test_autoware

- .github/workflows/test_autoware.yaml
- README.md
- compare/makereport_and_compare.sh
- docker/Dockerfile
- docker/Dockerfile_galactic.dockerfile
- docker/Dockerfile_humble
> ci: add settings for Ubuntu22.04, ROS2 Humble

- docker/Dockerfile
> ci: fix warnings in dockerfile

- analyze_node/analyze_node.py
- analyze_path/README.md
- analyze_path/add_path_to_architecture.py
- analyze_path/analyze_path.py
- check_callback_sub/check_callback_sub.py
- check_callback_timer/check_callback_timer.py
- make_report.py
- make_report.sh
> perf: improve processing time

- README.md
- docker/Dockerfile
- docker/Dockerfile_galactic.dockerfile
- sample_autoware/README.md
> docs: fix broken links

- README.md
- analyze_node/analyze_node.py
- analyze_path/add_path_to_architecture.py
- analyze_path/analyze_path.py
- check_callback_sub/check_callback_sub.py
- check_callback_timer/check_callback_timer.py
> fix: modify code for new CARET APIs

- .github/workflows/test_autoware.yaml
- docker/Dockerfile
- docker/Dockerfile_galactic.dockerfile
- sample_autoware/target_path_for_ci.json
> ci: fix target_path for old trace log

- analyze_node/analyze_node.py
- analyze_path/analyze_path.py
- check_callback_sub/check_callback_sub.py
- check_callback_timer/check_callback_timer.py
- common/utils.py
- compare/makereport_and_compare.sh
> ci: round float value in yaml

- sample_autoware/README.md
> docs: modify build process for Autoware (Humble)

- sample_autoware/package_list.json
> ci: fix package list

- .github/workflows/test_autoware.yaml
- docker/Dockerfile
- docker/README.md
- docker/entrypoint.sh
> ci: modify Dockerfile to add normal user and to specify CARET version

- report/analyze_node/analyze_node.py
- report/analyze_path/analyze_path.py
- report/check_callback_timer/check_callback_timer.py
- validation/callback/validate_callback.py
- validation/topic/validate_topic.py
> fix: use new CARET API for plot

- sample_autoware/README.md
> docs: update explanation to analyze Autoware with CARET

- docker/Dockerfile_galactic.dockerfile
> ci: fix pip version for Galactic

- .cspell.json
- docker/Dockerfile
- docker/Dockerfile_galactic.dockerfile
- docker/entrypoint.sh
- report/find_valid_duration/find_valid_duration.sh
pre-commit.ci failed with following log.
```
shellcheck...............................................................Failed
- hook id: shellcheck
- exit code: 1
In docker/entrypoint.sh line 25:
cd /work
^------^ SC2164 (warning): Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
Did you mean: 
cd /work || exit
In docker/entrypoint.sh line 26:
export trace_data=/${trace_data_name}
^----------------^ SC2154 (warning): trace_data_name is referenced but not assigned.
In report/find_valid_duration/find_valid_duration.sh line 9:
trace_data_name=$(basename "${trace_data}")
^-------------^ SC2034 (warning): trace_data_name appears unused. Verify use (or export if used externally).
For more information:
https://www.shellcheck.net/wiki/SC2034 -- trace_data_name appears unused. V... …
```
> fix: pre-commit ci failure

- report/validate_callback/validate_callback.py
Callback latency validation has been added.  
When a callback function is triggered by a timer, its latency is expected to be less than the timer's duration.  
The expected latency values are derived from `callback_list.csv`, which defines the expected frequency.
The latency validation results will appear in `index_LATENCY.html`.  
Additionally, results will be available in `validate_callback/{node_name}.html`.  
Test with Autoware workflow has passed.
https://github.com/tier4/caret_report/actions/runs/14127405760
Latency validation results do not affect `validate_callback/index.html` or `index.html`.  
This is because if a callback's latency exceeds the timer duration, the frequency will also be lower than expected.
> feat: add callback latency validation
